### ISSUE TITLE
Misspelled "Quadot" instead of "Qodot"

### ISSUE THREAD

**Issue by DeerTears** [nezvers/Godot_goodies#3]
**current name in the list:**
Quadot - Quake map support

**suggested replacement:**
Qodot - Quake map support

You can double check the spelling on the official repo: https://github.com/Shfty/qodot-plugin/ The link doesn't need to change, just the name for it.

Just something I noticed and thought I should point out ^  ^; Thanks so much for making this list!

**Comment by nezvers** [comment]
Sorry for noticing this late, but thanks for pointing it out!
